version: '3.6'

volumes:
  app-db-data:
  nats_streaming_1:
  app-db-sqlite:

services:
  db:
    image: postgres:11.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: coin_explorer_new
      POSTGRES_USER: noah
      POSTGRES_PASSWORD: password
    volumes:
      - app-db-data:/var/lib/postgresql/data

  nats-1:
    image: "nats:2"
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  nats-streaming-1:
    image: "nats-streaming:0.16.2-linux"
    command: >
      -store memory -max_msgs 0 -max_bytes 0 -cluster_id event -cluster_log_path /data_node/logs
      -cluster_peers node_1
      -nats_server nats://nats-1:4222
    depends_on:
      - nats-1
    volumes:
      - nats_streaming_1:/data_node

  coin-extender:
    build:
      context: .
    container_name: coin-extender
    environment:
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: noah
      DB_PASSWORD: password
      DB_NAME: coin_explorer_new
      NOAH_API_NODE: http://localhost:8841
      COIN_EXTENDER_API_HOST: localhost
      COIN_EXTENDER_API_PORT: 10000
      DEBUG: "true"
      NATS_CLUSTER_ID: event
      NATS_ADDR: nats://nats-1:4222
    depends_on:
      - db
      - nats-1
      - nats-streaming-1
    volumes:
      - app-db-sqlite:/db/sqlite
