version: '3.6'

volumes:
  app-db-data2:

services:
  db:
    image: postgres:9.5.14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: coin_explorer
      POSTGRES_USER: noah
      POSTGRES_PASSWORD: password
    volumes:
      - app-db-data2:/var/lib/postgresql/data
